name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "Docker/docker-compose.yml"
        down-flags: "--build -d"
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          username: ${{ secrets.USERNAME }}
          command_timeout: 20m
          script: |
            cd back
            git pull https://${{secrets.PAT}}@github.com/NullHeads/analitics-server.git main
            cd Docker
            echo "${{secrets.PASS}}" | sudo -S docker-compose up -d --build