name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          username: ${{ secrets.USERNAME }}
          command_timeout: 20m
          script: |
            cd back
            git pull https://${{secrets.PAT}}@github.com/NullHeads/analitics-server.git main
            cd Docker
            echo "${{secrets.PASS}}" | sudo -S docker-compose up -d --build